Require Import Cat Relations.
Require LL aarch64_obsolete aarch64 aarch64fences arm_alt arm armfences armllh atom_arm atom c11_base c11_cos c11_los c11_orig c11_partialSC c11_simp compat cos coscat cross doc64 fences filters fulleieio herd herdcat lessrelaxed mini minimal minimalcat mips_tso mips mipsfences naked ppc_checks ppc ppcfences ppo pretty prettycat qualcomm rc11 riscv_defs riscv_total riscv sc sc2 sccat simple_arm simple_c11 stdlib tso uni uniproc_sca uniproc_normw_cat uniproc uniproccat x86fences x86tso.

Check LL.valid.
Check aarch64_obsolete.valid.
Check aarch64.valid.
Check aarch64fences.valid.
Check arm_alt.valid.
Check arm.valid.
Check armfences.valid.
Check armllh.valid.
Check atom_arm.valid.
Check atom.valid.
Check c11_base.valid.
Check c11_cos.valid.
Check c11_los.valid.
Check c11_orig.valid.
Check c11_partialSC.valid.
Check c11_simp.valid.
Check compat.valid.
Check cos.valid.
Check coscat.valid.
Check cross.valid.
Check doc64.valid.
Check fences.valid.
Check filters.valid.
Check fulleieio.valid.
Check herd.valid.
Check herdcat.valid.
Check lessrelaxed.valid.
Check mini.valid.
Check minimal.valid.
Check minimalcat.valid.
Check mips_tso.valid.
Check mips.valid.
Check mipsfences.valid.
Check naked.valid.
Check ppc_checks.valid.
Check ppc.valid.
Check ppcfences.valid.
Check ppo.valid.
Check pretty.valid.
Check prettycat.valid.
Check qualcomm.valid.
Check rc11.valid.
Check riscv_defs.valid.
Check riscv_total.valid.
Check riscv.valid.
Check sc.valid.
Check sc2.valid.
Check sccat.valid.
Check simple_arm.valid.
Check simple_c11.valid.
Check stdlib.valid.
Check tso.valid.
Check uni.valid.
Check uniproc_sca.valid.
Check uniproc_normw_cat.valid.
Check uniproc.valid.
Check uniproccat.valid.
Check x86fences.valid.
Check x86tso.valid.
